name: Despliegue con Docker
on:
  push:
    branches: [ main ] # O el nombre de tu rama principal

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Levantar Docker
        run:
          docker compose down 
          docker compose up -d --build