name: Despliegue Automático MERN
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: 1. Descargar código
        uses: actions/checkout@v4

      - name: 2. Debug - ¿Dónde estamos?
        run: ls -R

      - name: 3. Preparar Backend
        run: |
          # Si tu package.json está directamente en backend:
          cd backend 
          npm install
          npm run build

      - name: 4. Preparar Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: 5. Reiniciar PM2
        run: |
          pm2 delete backend || true
          pm2 start /home/ari/actions-runner/_work/TFG_Kanban/TFG_Kanban/backend/dist/main.js --name "backend"
          pm2 save