name: Despliegue con Docker MERN
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: 1. Descargar código nuevo de GitHub
        uses: actions/checkout@v4

      - name: 2. Levantar la infraestructura con Docker
        run: |
          docker compose up -d --build